name: divain-project
services:
  # frontend:
  #   build:
  #     context: front
  #     dockerfile: front/Dockerfile
  #     target: development
  #   networks:
  #     - client-sid
  #   ports:
  #     - 3000:3000

  api:
    build:
      context: back
      dockerfile: back/Dockerfile
      target: development
    env_file: back/.env
    container_name: fastapi_app
    networks:
      # - client-side
      - server-side
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - db-data:/var/lib/postgresql/data

