name: divain-project
services:
  # frontend:
  #   build:
  #     context: front
  #     dockerfile: front/Dockerfile
  #   networks:
  #     - client-sid
  #   ports:
  #     - 3000:3000

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file: 
      - .env

    # networks:
    #   # - client-side
    #   - server-side

  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: